build: converted Utils class in module
matteoredz/itax-code pull request #53
Opened 2024-04-07 12:26 UTC by roccoemanuelebonanno

n this PR, I have converted the Utils class into a module because, in my opinion, using a class is unnecessary in this case. Modules are mainly used to group common functionalities and enable their reuse.

2024-05-01 09:22 UTC, matteoredz requested changes

2024-05-01 09:22 UTC, matteoredz commented on lib/itax_code/encoder.rb
> +    def initialize(data = {}, utils = ItaxCode::Utils)
The prefix is unnecessary here, as you're already inside the `ItaxCode` module.

```suggestion
    def initialize(data = {}, utils = Utils)
```

2024-05-01 09:22 UTC, matteoredz commented on lib/itax_code/omocode.rb
> +    def initialize(tax_code, utils = ItaxCode::Utils)
The prefix is unnecessary here, as you're already inside the ItaxCode module.

```suggestion
    def initialize(tax_code, utils = Utils)
```

2024-05-01 09:22 UTC, matteoredz commented on lib/itax_code/parser.rb
> +    def initialize(tax_code, utils = ItaxCode::Utils)
The prefix is unnecessary here, as you're already inside the ItaxCode module.

```suggestion
    def initialize(tax_code, utils = Utils)
```

2024-05-01 09:22 UTC, matteoredz commented on lib/itax_code/version.rb
> +  VERSION = "2.1.0"
The versions mustn't be bumped manually, as it's automatically done by the [release-please-action](https://github.com/matteoredz/itax-code/blob/main/.github/workflows/release.yml#L24) upon merging a release PR.

```suggestion
  VERSION = "2.0.3"
```

2024-05-01 09:22 UTC, matteoredz commented on lib/itax_code/utils.rb
While it's ok to convert this class to a module, I discourage sorting the methods in it, preserving the original order, to make the review easier and avoid unnecessary noise.

2024-05-01 09:24 UTC, matteoredz commented
@roccoemanuelebonanno the PR title should be updated too. While it's correctly applying the conventional commits, the changes here are not about `build` but more `chore`, `refactor`, or `perf`.

2024-05-01 09:35 UTC, matteoredz commented
Also, to make the Rubocop linter happy, we should exclude the new Utils module from the following rule:

```
lib/itax_code/utils.rb:7:3: C: Metrics/ModuleLength: Module has too many lines. [121/100]
  module Utils ...
  ^^^^^^^^^^^^
```

This can be done by moving [this directive](https://github.com/matteoredz/itax-code/blob/main/.rubocop.yml#L41) from the current location to a new rule (ab sorted):

```yaml
Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - 'lib/itax_code/utils.rb'
```

2024-05-01 10:18 UTC, roccoemanuelebonanno commented on lib/itax_code/utils.rb
Some methods have been moved to private scope because they are only used by the module itself. The order of the other methods has not been changed.

2024-05-02 11:22 UTC, matteoredz approved these changes
LGTM, thanks for the PR 🥳

2024-05-02 11:22 UTC, matteoredz commented
I see an error from the CodeClimate check, but it's unrelated to this PR. I'll address it in another context.

2024-05-02 11:23 UTC, merged